//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlightReservation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class airport
    {
        public string APcode { get; set; }
        public string APname { get; set; }
        public string Zipcode { get; set; }
        public string City { get; set; }
        public string State { get; set; }
    }
}
