//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlightReservation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class credit_card
    {
        public string Cnum { get; set; }
        public short Ctype { get; set; }
        public short ExMonth { get; set; }
        public int ExYear { get; set; }
        public long Pid { get; set; }
    }
}
