//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Airline.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Airline_ModelEntities : DbContext
    {
        public Airline_ModelEntities()
            : base("name=Airline_ModelEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<account> account { get; set; }
        public virtual DbSet<aircraft> aircraft { get; set; }
        public virtual DbSet<aircraft_seats> aircraft_seats { get; set; }
        public virtual DbSet<credit_card> credit_card { get; set; }
        public virtual DbSet<flight> flight { get; set; }
        public virtual DbSet<location> location { get; set; }
        public virtual DbSet<passenger> passenger { get; set; }
        public virtual DbSet<seat_class> seat_class { get; set; }
        public virtual DbSet<ticket> ticket { get; set; }
    }
}
