//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Airline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ticket
    {
        public long Tid { get; set; }
        public float Price { get; set; }
        public bool Status { get; set; }
        public int SeatNum { get; set; }
        public short SeatClass { get; set; }
        public long Fid { get; set; }
        public long Pid { get; set; }
        public long Num_of_bags { get; set; }
    }
}
